# Generated by Django 3.0.5 on 2020-04-09 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_auto_20200409_2038'),
        ('auth', '0011_update_proxy_permissions'),
        ('admin', '0004_auto_20200409_2038'),
        ('users', '0002_auto_20200409_2029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
